---
namespace: fmjstudios
name: runtimes
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: Ansible Collection for language runtime setup and configuration
license_file: "LICENSE"
tags:
  - runtimes
  - php
  - php-fpm
  - node.js
  - node
  - ruby
  - java
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: https://fmj.dev
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github