---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - php_install
        - php_configure
        - php_run
  tags:
    - php_install
    - php_configure
    - php_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - php_install
  tags:
    - php_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - php_configure
  tags:
    - php_configure

- name: Flush handlers after run.
  ansible.builtin.meta: flush_handlers
