---
- name: preflight | Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: preflight | Install package fact dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _pkg_fact_req }}"
    state: present
  when: (_pkg_fact_req)
  vars:
    _pkg_fact_req: "{% if (ansible_pkg_mgr == 'apt') %}\
      {{ ('python-apt' if ansible_python_version is version('3', '<') else 'python3-apt') }}
      {% else %}\
      {% endif %}"

- name: preflight | Gather package facts
  ansible.builtin.package_facts:
  when: "not 'packages' in ansible_facts"
# - name: preflight | Assert that the PHP installation variables are correctly set
#   ansible.builtin.assert:
#     that:
#       - php_package_source is defined
#       - php_package_source is string
#       - php_package_source is match ('^(os|ppa)$')
#       - php_version is defined
#       - php_version is string
#       - lookup('php_dependencies', item) is defined
#       - php_dependencies is iterable
#       - lookup('php_extensions', item) is defined
#       - php_extensions is iterable
#       - php_ini is defined
#       - php_ini is mapping
